services:
  postgres:
    image: postgres:13
    container_name: postgres-dev
    environment:
      POSTGRES_USER: furniture_admin_user
      POSTGRES_PASSWORD: furniture_admin_password
      POSTGRES_DB: furniture-sales
    ports:
      - "5432:5432"  # standard is the same inside:outside
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data on the host machine
    networks:
      - dev-network
volumes:
  postgres-data:  # This ensures data persists even if the container is recreated
networks:
  dev-network:
    driver: bridge