FROM openjdk:17-jdk-slim

# working directory
WORKDIR /app

# Target file to docker folder and name
COPY target/office-furniture-sales app.jar

# port 8080 to the outside
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]